import type { MoneyMarketFund } from "@/types/MoneyMarketFund";

export const moneyMarketFund: MoneyMarketFund[] = [
  {
    rank: 1,
    name: "Enwealth Money Market Fund",
    fund_manager: "Enwealth Financial Services",
    initial_minimum_investment: 1000,
    annual_yield: "11.43%",
  },
  {
    rank: 2,
    name: "Etica Money Market Fund",
    fund_manager: "Etica Capital Limited",
    initial_minimum_investment: 1000,
    annual_yield: "11.41%",
  },
  {
    rank: 3,
    name: "Cytonn Money Market Fund",
    fund_manager: "Cytonn Asset Managers Limited",
    initial_minimum_investment: 1000,
    annual_yield: "11.41%",
  },
  {
    rank: 4,
    name: "Apollo Money Market Fund",
    fund_manager: "Apollo Asset Management Company Limited",
    initial_minimum_investment: 1000,
    annual_yield: "10.95%",
  },
  {
    rank: 5,
    name: "GenAfrica Money Market Fund",
    fund_manager: "GenAfrica Asset Managers Limited",
    initial_minimum_investment: 1000,
    annual_yield: "10.77%",
  },
  {
    rank: 6,
    name: "Jubilee Money Market Fund",
    fund_manager: "Jubilee Financial Services Limited",
    initial_minimum_investment: 2000,
    annual_yield: "10.75%",
  },
  {
    rank: 7,
    name: "Madison Money Market Fund",
    fund_manager: "Madison Investment Managers Limited",
    initial_minimum_investment: 5000,
    annual_yield: "10.64%",
  },
  {
    rank: 8,
    name: "Zimele Money Market Fund",
    fund_manager: "Zimele Asset Management",
    initial_minimum_investment: 1000,
    annual_yield: "10.56%",
  },
  {
    rank: 9,
    name: "Old Mutual Money Market Fund",
    fund_manager: "Old Mutual Investment Group",
    initial_minimum_investment: 2000,
    annual_yield: "10.50%",
  },
  {
    rank: 10,
    name: "Co-op Money Market Fund",
    fund_manager: "Co-op Trust Investment Services Limited",
    initial_minimum_investment: 2000,
    annual_yield: "10.45%",
  },
  {
    rank: 11,
    name: "Kuza Money Market Fund",
    fund_manager: "Kuza Asset Management Limited",
    initial_minimum_investment: 5000,
    annual_yield: "10.45%",
  },
  {
    rank: 12,
    name: "Nabo Africa Money Market Fund",
    fund_manager: "Nabo Capital Limited",
    initial_minimum_investment: 10000,
    annual_yield: "10.23%",
  },
  {
    rank: 13,
    name: "African Alliance Kenya Money Market Fund",
    fund_manager: "African Alliance",
    initial_minimum_investment: 100000,
    annual_yield: "10.19%",
  },
  {
    rank: 14,
    name: "GenCap Hela Imara Fund",
    fund_manager: "Genghis Capital",
    initial_minimum_investment: 1000,
    annual_yield: "10.10%",
  },
  {
    rank: 15,
    name: "Sanlam Money Market Fund",
    fund_manager: "Sanlam Investments East Africa Limited",
    initial_minimum_investment: 2500,
    annual_yield: "10.06%",
  },
];
