export const saccos = [
  {
    rank: 1,
    sacco: "Nyati Sacco",
    registration_fee: 500,
    minimum_monthly_contribution: 1200,
    share_on_capital: 9000,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "21%",
    interest_in_member_deposit: "11%",
  },
  {
    rank: 2,
    sacco: "Magadi SACCO",
    registration_fee: 2000,
    minimum_monthly_contribution: 3000,
    share_on_capital: 20000,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "20%",
    interest_in_member_deposit: "14%",
  },
  {
    rank: 3,
    sacco: "Tower SACCO",
    registration_fee: 500,
    minimum_monthly_contribution: 500,
    share_on_capital: 10000,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "20%",
    interest_in_member_deposit: "13%",
  },
  {
    rank: 4,
    sacco: "Mombasa Port SACCO",
    registration_fee: 500,
    minimum_monthly_contribution: 1000,
    share_on_capital: 40000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "20%",
    interest_in_member_deposit: "12.5%",
  },
  {
    rank: 5,
    sacco: "Waumini SACCO",
    registration_fee: 500,
    minimum_monthly_contribution: 1000,
    share_on_capital: 15000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "19.25%",
    interest_in_member_deposit: "13%",
  },
  {
    rank: 6,
    sacco: "TransNation SACCO",
    registration_fee: 500,
    minimum_monthly_contribution: 500,
    share_on_capital: 10000,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "18%",
    interest_in_member_deposit: "13.1%",
  },
  {
    rank: 7,
    sacco: "Biashara SACCO",
    registration_fee: 2000,
    minimum_monthly_contribution: 2500,
    share_on_capital: 50000,
    maximum_loan_multiple: 5,
    dividend_on_share_capital: "18%",
    interest_in_member_deposit: "13%",
  },
  {
    rank: 8,
    sacco: "Bandari SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 1500,
    share_on_capital: 10500,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "18%",
    interest_in_member_deposit: "11.5%",
  },
  {
    rank: 9,
    sacco: "Mafanikio SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 1500,
    share_on_capital: 10500,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "18%",
    interest_in_member_deposit: "11%",
  },
  {
    rank: 10,
    sacco: "Hazina SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 100,
    share_on_capital: 16000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "18%",
    interest_in_member_deposit: "10.6%",
  },
  {
    rank: 11,
    sacco: "Kenya Police SACCO",
    registration_fee: 2000,
    minimum_monthly_contribution: 1000,
    share_on_capital: 20000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "17%",
    interest_in_member_deposit: "10.8%",
  },
  {
    rank: 12,
    sacco: "Unison SACCO",
    registration_fee: 2000,
    minimum_monthly_contribution: 2000,
    share_on_capital: 15000,
    maximum_loan_multiple: 5,
    dividend_on_share_capital: "16%",
    interest_in_member_deposit: "12.5%",
  },
  {
    rank: 13,
    sacco: "Sheria SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 2000,
    share_on_capital: 20000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "16%",
    interest_in_member_deposit: "9%",
  },
  {
    rank: 14,
    sacco: "Nation SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 2000,
    share_on_capital: 10000,
    maximum_loan_multiple: 2,
    dividend_on_share_capital: "15%",
    interest_in_member_deposit: "9%",
  },
  {
    rank: 15,
    sacco: "Kimisitu SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 2000,
    share_on_capital: 30000,
    maximum_loan_multiple: 4,
    dividend_on_share_capital: "15%",
    interest_in_member_deposit: "8.5%",
  },
  {
    rank: 16,
    sacco: "Stima SACCO",
    registration_fee: 500,
    minimum_monthly_contribution: 1000,
    share_on_capital: 25000,
    maximum_loan_multiple: 5,
    dividend_on_share_capital: "14%",
    interest_in_member_deposit: "11%",
  },
  {
    rank: 17,
    sacco: "Imarika SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 1000,
    share_on_capital: 30000,
    maximum_loan_multiple: 2,
    dividend_on_share_capital: "14%",
    interest_in_member_deposit: "8%",
  },
  {
    rank: 18,
    sacco: "Imarisha SACCO",
    registration_fee: 360,
    minimum_monthly_contribution: 1000,
    share_on_capital: 30000,
    maximum_loan_multiple: 5,
    dividend_on_share_capital: "13.9%",
    interest_in_member_deposit: "11.2%",
  },
  {
    rank: 19,
    sacco: "Mwalimu SACCO",
    registration_fee: 2000,
    minimum_monthly_contribution: 2000,
    share_on_capital: 30000,
    maximum_loan_multiple: 6,
    dividend_on_share_capital: "13%",
    interest_in_member_deposit: "9.3%",
  },
  {
    rank: 20,
    sacco: "Safaricom SACCO",
    registration_fee: 1000,
    minimum_monthly_contribution: 3000,
    share_on_capital: 40000,
    maximum_loan_multiple: 3,
    dividend_on_share_capital: "13%",
    interest_in_member_deposit: "8.2%",
  },
];
